services:
  db:
    image: postgres:17-alpine
    container_name: lostandfound-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # This tells Docker to ping the DB until it is fully ready
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lostandfound-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}?stringtype=unspecified
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      SPRING_PROFILES_ACTIVE: dev
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL}
    volumes:
      - app_logs:/app/logs
      - ./uploads:/app/uploads

volumes:
  postgres_data:
  app_logs:
