CREATE TABLE post_bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  CONSTRAINT fk_post_bookmarks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_post_bookmarks_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
  CONSTRAINT uq_user_post_bookmark UNIQUE (user_id, post_id)
);

CREATE INDEX idx_post_bookmarks_user_id ON post_bookmarks (user_id);

CREATE INDEX idx_post_bookmarks_post_id ON post_bookmarks (post_id);

