CREATE TABLE users (
    -- Primary Key (Mapped from Long ID with IDENTITY generation)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BaseEntity Audit Fields
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,

    -- User Fields
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    token VARCHAR(512),

    -- Profile Fields
    display_name VARCHAR(255),
    contact_info VARCHAR(255)

    -- Note: profile_image_id will be added via an ALTER TABLE in a future migration 
    -- once the 'images' table is created to ensure proper foreign key constraints.
);

-- Indexes for performance on frequently queried columns
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_is_active ON users(is_active);
