-- ==========================================
-- 1. USERS TABLE
-- ==========================================
CREATE TABLE users (
    -- Primary Key
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BaseEntity Audit Fields
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                       deleted_at TIMESTAMP WITHOUT TIME ZONE,

    -- User Fields
                       email VARCHAR(255) NOT NULL UNIQUE,
    -- NOTE: password is now NULLABLE to support Google OAuth users!
                       password VARCHAR(255),
    -- NOTE: provider tracks how they logged in (LOCAL or GOOGLE)
                       provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
                       role VARCHAR(50) NOT NULL DEFAULT 'USER',
                       is_locked BOOLEAN NOT NULL DEFAULT FALSE,
                       token VARCHAR(512),

    -- Profile Fields
                       display_name VARCHAR(255),
                       contact_info VARCHAR(255)

    -- Note: profile_image_id will be added via an ALTER TABLE in a future migration
    -- once the 'images' table is created.
);

-- Indexes for performance on frequently queried columns
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_is_active ON users(is_active);


-- ==========================================
-- 2. REFRESH TOKENS TABLE
-- ==========================================
CREATE TABLE refresh_tokens (
    -- Primary Key
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BaseEntity Audit Fields
                                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                deleted_at TIMESTAMP WITHOUT TIME ZONE,

    -- RefreshToken Specific Fields
                                user_id BIGINT NOT NULL,
                                token VARCHAR(512) NOT NULL UNIQUE,
                                expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                revoked BOOLEAN NOT NULL DEFAULT FALSE,

    -- Foreign Key linking to the users table
                                CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Index for lightning-fast token lookups
CREATE INDEX idx_rt_token ON refresh_tokens(token);


-- ==========================================
-- 3. PASSWORD RESET TOKENS TABLE
-- ==========================================
CREATE TABLE password_reset_tokens (
    -- Primary Key
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BaseEntity Audit Fields
                                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                       deleted_at TIMESTAMP WITHOUT TIME ZONE,

    -- Reset Token Specific Fields
                                       user_id BIGINT NOT NULL,
                                       token VARCHAR(512) NOT NULL UNIQUE,
                                       expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    -- Foreign Key linking to the users table (One-to-One style constraint)
                                       CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Index for token lookups during the reset confirmation step
CREATE INDEX idx_prt_token ON password_reset_tokens(token);