CREATE TABLE refresh_tokens (
    -- Primary Key
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- BaseEntity Audit Fields
                                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                deleted_at TIMESTAMP WITHOUT TIME ZONE,

    -- RefreshToken Specific Fields
                                user_id BIGINT NOT NULL,
                                token VARCHAR(512) NOT NULL UNIQUE,
                                expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                revoked BOOLEAN NOT NULL DEFAULT FALSE,

    -- Foreign Key linking to the users table
                                CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Index for lightning-fast token lookups
CREATE INDEX idx_rt_token ON refresh_tokens(token);